### ISSUE TITLE
Fix counter for 4-digit number of tabs

### ISSUE THREAD

**Issue by XCanG** [DaAwesomeP/tab-counter#11]
This is how it look (title are dupplicated and full count of tabs not fit in window):

![](https://lolisafe.moe/F5QCqPxK.png)

**Comment by DaAwesomeP** [comment]
I'm not sure what is preventing the popup from resizing to fit the text. It looks like there was some draw glitch or artifact though in the top left of the popup. I'll look into it. The popup could look a little nicer too.

I should make a tab count contest or something! That's impressive. Gotta love FF x64. Just wondering, but how is the performance of the counter with that many tabs? I'd love to note on the addon page that it can handle 1800+ tabs!

**Comment by XCanG** [comment]
@DaAwesomeP first of all I use Nightly build (FF 60), I also use several addons to help me sorting it and increase perfomance:
* [Tree Style Tab](https://addons.mozilla.org/ru/firefox/addon/tree-style-tab/) with following styles (make it more compact and informational at same time):
```CSS
.tab { font-weight: 300; font-family: "Segoe UI"; padding: 0; height: 20px !important; border-color: rgba(0, 0, 0, .1); position: relative; display: flex; }
.tab:hover { overflow: visible; opacity: 1 !important; }
.tab.unread .label { color: gray !important; font-style: italic !important; }
.tab.private-browsing .label:before { content: "🕶"; }
.tab .closebox { opacity: .05; position: absolute; top: 5px; right: 3px; /*padding: 5px 3px;*/ height: 17px; cursor: pointer; /*transition: opacity .2s ease-out;*/ z-index: 1000; } .tab:hover .closebox { opacity: .6; background-color: #999; }
.tab.discarded { opacity: .6; }
.tab:hover .label { position: absolute; top: 0px; font-weight: 700; background: rgba(255, 255, 255, .6); width: 100%; word-wrap: break-word; word-break: break-all; text-overflow: clip; white-space: pre-wrap; line-height: 1.2 !important; color: black; pointer-events: none; z-index: 1000; animation: extend .8s linear 0s; /*animation: marq 3s linear 1s infinite alternate;*/ }
@keyframes marq { 0% { text-indent: calc(0% + 15px); } 100% { text-indent: calc(0% - 200px); } }
@keyframes extend { 0% { max-height: 20px; } 100% { max-height: 200px; } }
```
* [Auto Tab Discard](https://addons.mozilla.org/ru/firefox/addon/auto-tab-discard/) what unloading tabs after one hour of inactivity excuding several sites, such as mail, youtube, e.t.c. what is important to not unload
* [PopUp](https://addons.mozilla.org/ru/firefox/addon/popup/) for moving some tabs I need to see on top of other (make compact new windows what later via windows externl tool I can make always on top, set transparency or/and clickable through)

In the result I keep clean view of tabs at the left, I also see which tab is loaded and which not. Unnessesary to keep tabs are unloaded (they still probably consume RAM, but not CPU).

This is CPU and RAM usage:
![default](https://user-images.githubusercontent.com/4011523/35612472-b4d85034-068a-11e8-9d61-abb4a0d04aea.png)
It take not much CPU and work pretty fast (I have CPU i7-4820k), the only you need is have RAM for it, at the moment my Firefox instance runned for a week (not restarting) and it consume totally 11 Gb of RAM. If I restart it (make clean load), with this amount of tabs it will take 4-5 Gb.
